// SPDX-FileCopyrightText: 2026 ChipDesign B.V.
// SPDX-License-Identifier: Apache-2.0
//
// GENERATED by scripts/gen_fsm_bench.py -- do not edit by hand.
//
// Illegal state recovery for cdriscv_lsu, on its gate netlist.
// See coverage waiver W2a and finding V24.

`default_nettype none
`timescale 1ns/1ps

module tb_fsm_cdriscv_lsu;

  logic clk = 0, rst_n;
  always #5ns clk = ~clk;

  logic  tb_req_i;
  logic  tb_we_i;
  logic [1:0] tb_size_i;
  logic  tb_sign_ext_i;
  logic [31:0] tb_addr_i;
  logic [31:0] tb_wdata_i;
  logic  tb_kill_i;
  logic  tb_data_gnt_i;
  logic  tb_data_rvalid_i;
  logic [31:0] tb_data_rdata_i;
  logic  tb_data_err_i;

  cdriscv_lsu u_dut (
      .clk_i (clk),
      .rst_ni (rst_n),
      .req_i (tb_req_i),
      .we_i (tb_we_i),
      .size_i (tb_size_i),
      .sign_ext_i (tb_sign_ext_i),
      .addr_i (tb_addr_i),
      .wdata_i (tb_wdata_i),
      .kill_i (tb_kill_i),
      .busy_o (),
      .valid_o (),
      .rdata_o (),
      .err_o (),
      .data_req_o (),
      .data_gnt_i (tb_data_gnt_i),
      .data_rvalid_i (tb_data_rvalid_i),
      .data_we_o (),
      .data_be_o (),
      .data_addr_o (),
      .data_wdata_o (),
      .data_rdata_i (tb_data_rdata_i),
      .data_err_i (tb_data_err_i)
  );

  int errors = 0, checks = 0;
  logic [2:0] idle, got;
  int e;

  task automatic do_reset;
    rst_n = 0;
    tb_req_i = '0;
    tb_we_i = '0;
    tb_size_i = '0;
    tb_sign_ext_i = '0;
    tb_addr_i = '0;
    tb_wdata_i = '0;
    tb_kill_i = '0;
    tb_data_gnt_i = '1;
    tb_data_rvalid_i = '1;
    tb_data_rdata_i = '0;
    tb_data_err_i = '0;
    repeat (4) @(posedge clk);
    rst_n = 1;
    repeat (4) @(posedge clk);
  endtask

  initial begin
    do_reset();
    idle = u_dut.state_q;

    for (e = 0; e < 8; e++) begin
      do_reset();
      force u_dut.state_q = 3'(e);
      @(posedge clk);
      #1ns;
      release u_dut.state_q;
      repeat (8) @(posedge clk);
      checks++;
      got = u_dut.state_q;
      if (got === 3'bx) begin
        $display("[fsm-cdriscv_lsu] FAIL: encoding %0d led to X", e);
        errors++;
      end else if (got !== idle) begin
        $display("[fsm-cdriscv_lsu] FAIL: encoding %0d settled at %0d, not idle %0d",
                 e, got, idle);
        errors++;
      end
    end

    if (errors == 0)
      $display("[fsm-cdriscv_lsu] PASS: 8 encodings all recover to idle");
    else
      $display("[fsm-cdriscv_lsu] FAIL: %0d of %0d", errors, checks);
    $finish;
  end

  initial begin #5ms; $display("[fsm-cdriscv_lsu] FAIL: timeout"); $finish; end

endmodule
